### PR TITLE
Fixed devtools warning

### PR DESCRIPTION
**Pull request by MasicoreLord**

### CODE REVIEW

**Comment by MasicoreLord** [comment]
Not needed

**Comment by joe27g** [comment]
If you recreate this without the end of support notice, i'll merge it, because like you said, "Memes are a part of ED after all." :^)

**Comment by MasicoreLord** [comment]
@joe27g give me a moment to do so, and I'll reopen it w/ the notice taken out

**Comment by MasicoreLord** [comment]
Took out that notice

**Pull request merged**
