### PR TITLE
Added support for events other than click to settings page

### PR DESCRIPTION
**Pull request by YouKnowBlom**
Useful for sliders and color pickers. Will require non official plugins to update (simple fix).

_A lot of the changes are from doing >reindent lines in vs code_

### CODE REVIEW

**Comment by rauenzi** [comment]
I would personally not approve this change. It opts for `forEach` which is significantly slower than for loops. As a nitpick indentation should be dictated by the codebase and contributors should match what they are doing not vice versa.

**Comment by YouKnowBlom** [comment]
My bad, didnt know foreach was discouraged😊. Would a rewrite with for instead of foreach be sufficient?

I will update my indentation settings as well, although it seems to only have indented empty lines for some reason.

**Comment by YouKnowBlom** [comment]
Ill fix the mentioned issues and also try to add some sort of backwards compatibility. Then its up to you @joe27g to merge if you think it's of quality 😄

**Comment by jakuski** [comment]
I approve of this change since being restricted to `onclick` when working with different UI elements such as text inputs ain't great.

**Comment by joe27g** [comment]
I agree with @jakuski, this was something that needed to be done eventually, so why not now :)

**Pull request merged**
