### PR TITLE
Fixed dom_shit to save plugin settings

### PR DESCRIPTION
**Pull request by d1rty-dan**

### CODE REVIEW

**Comment by rauenzi** [comment]
This PR has conflicts, please fix before a review.

**Comment by rauenzi** [comment]
Not quite the right way to do it. Should be making use of `loadPluginSettings` and `savePluginSettings`.

**Comment by d1rty-dan** [comment]
Aren't those present from lines 305 to 320> I simply reflected what the master branch has currently since the beta branch is what introduced this issue. Personally I haven't encountered any problems editing plugin configs with this change, but if you notice an issue let me know,

**Comment by rauenzi** [comment]
Yes, they are present, that is why you should make use of them rather than breaking DRY.

**Comment by ImportTaste** [comment]
It seems Discord made things even worse, I've been having issues where I can't even select some of the text boxes in the settings anymore. Hopefully you can fix that too.

**Comment by joe27g** [comment]
> the beta branch is what introduced this issue.

What exactly is the issue? Saving and loading plugin configs works fine on beta from my testing.

**Comment by d1rty-dan** [comment]
I'm not sure if the beta branch creates this issue with all BD plugins, but the only BD plugins with configs I use are zere's and all of them fail to save their settings when I restart discord. With the old method of saving and loading plugins (in the previous master branch) this issue was not present. The file in this PR uses the beta file entirely except it uses the master branch's system of saving and loading plugins.

**Pull request closed without merging**
