### PR TITLE
Update dom_shit.js

### LINKED ISSUE #141: Can't watch streams on Linux
**Steps to reproduce**
1. Enter a voice channel when one or more people are streaming
2. Pop out the player in a new window
3. Click one of the stream thumbnails
4. It shows the loading animation indefinitely
5. Closing the window or ending the call will cause Discord to crash

This does not happen and streams are watchable when the player is still inside the main window.
This does not happen when ED is not injected.
This still happens with all plugins disabled.

**Desktop info**
OS: Ubuntu 20.04.1
Window manager: i3
ED: master (`71f79a0`)
Discord version:
> Stable 65705 (d72a93f)
> Host 0.0.11
> Linux 64-Bit (5.4.0-42-Generic)

### PR DESCRIPTION
**Pull request by llyyr**
Fixes #141

### CODE REVIEW

**Comment by katacarbix** [comment]
Just pulled it locally for testing and it partially solves the problem I was having! I can now watch streams in the pop-out window, however the Discord app still crashes when closing the player or hanging up.

**Comment by llyyr** [comment]
I can't reproduce that on my client, are you sure it's ED and not a plugin or something else?

**Comment by katacarbix** [comment]
When I did my initial testing I tried it with all plugins turned off. I can try it again but I expect similar results.

If I knew what was going on I could contribute code, but unfortunately I don't :\

**Comment by katacarbix** [comment]
Just tested it, same problem.

**Pull request merged**
